RUN apt-get -y install \
      realpath \
      curl \
      wget \
      git \
      python-pip \
      tar \
      bzip2 \
      locales \
      ca-certificates \
      software-properties-common  # for: add-apt-repository

toto